server.port=8080
spring.main.banner-mode=off
# 1. URL kết nối H2 DB (Lưu dữ liệu vào file trong thư mục ./data/ids_db)
spring.datasource.url=jdbc:h2:file:./data/ids_db;AUTO_SERVER=TRUE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# 2. Cấu hình JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# 3. Cho phép truy cập giao diện H2 Console trên trình duyệt (tùy chọn)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console